version: '3.8'

services:
  db:
    image: ankane/pgvector
    ports:
      - 5777:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    restart: always

volumes:
  db:
